# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: CmaUserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: cma_user_registration }
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
