<?php

namespace CmaAdminBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{
    function findLastNewsletterForMailing(){
        $qb = $this->createQueryBuilder('a');
        $qb->select('u')
            ->from($this->_entityName, 'u')
            ->where($qb->expr()->eq('u.finished', ':finished'))
            ->setMaxResults(1)
            ->setParameter('finished', 0);
        return $qb->getQuery()->getScalarResult();
    }
}
