services:
#    cma_user.groupserv.services:
#        class: CmaUserBundle\Services\groupServ
#    cma_user.example:
#        class: CmaUserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
#    cma.form.registration:
#       class: CmaUserBundle\Form\RegistrationType
#       tags: 
#           - { name: form.type, alias: cma_user_registration }
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]