services:
    cma_user.groupserv.services:
        class: CmaUserBundle\Services\groupServ
#    cma_user.example:
#        class: CmaUserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    cma.form.profile:
       class: CmaUserBundle\Form\ProfileType
       calls:
             - [setEntityManager, ["@doctrine.orm.entity_manager"]]