<?php

namespace CmaUserBundle\Repository;

/**
 * ComplainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplainRepository extends \Doctrine\ORM\EntityRepository
{
}
