<?php

namespace CmaUserBundle\Repository;

/**
 * EstimateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimateRepository extends \Doctrine\ORM\EntityRepository
{
}
