home_page_homepage:
    path:     /
    defaults: { _controller: homePageBundle:Default:index }

user_parameter:
    path:     /parameter
    defaults: { _controller: homePageBundle:User:parameter }

user_message:
    path:     /message
    defaults: { _controller: homePageBundle:User:message }

user_info:
    path:     /information
    defaults: { _controller: homePageBundle:User:information }

user_devis:
    path:     /devis
    defaults: { _controller: homePageBundle:User:devis }

user_progress_project:
    path:     /progressproject
    defaults: { _controller: homePageBundle:User:progress }

user_finish_project:
    path:     /finishproject
    defaults: { _controller: homePageBundle:User:finish }

user_sold_project:
    path:     /soldproject
    defaults: { _controller: homePageBundle:User:sold }

hello_the_world:
    path:     /hello-world
    defaults: { _controller: homePageBundle:Advert:index }

deleteuser:
    path:     /group/delete/{username}
    defaults: { _controller: homePageBundle:User:deleteadmin }

home_page_view:
    path:     /{id}
    defaults: { _controller: homePageBundle:Advert:view }
    requirements:
        id: \d+

listGalleries:
    path:     /galleries
    defaults: { _controller: homePageBundle:Gallery:index }

listArtists:
    path:     /artist
    defaults: { _controller: homePageBundle:Artist:index }

Artist_id:
    path:     /artist/{id}
    defaults: { _controller: homePageBundle:Artist:view }
    requirements:
        id: \d+
