home_page_homepage:
    path:     /
    defaults: { _controller: homePageBundle:Default:index }

user_parameter:
    path:     /parameter
    defaults: { _controller: homePageBundle:User:parameter }

piece_edit_id:
    path:     /piece/edit/{id}
    defaults: { _controller: homePageBundle:Piece:edit }

piece_edit:
    path:     /piece/edit
    defaults: { _controller: homePageBundle:Piece:create }

user_message:
    path:     /message
    defaults: { _controller: homePageBundle:User:message }

user_info:
    path:     /information
    defaults: { _controller: homePageBundle:User:information }

user_devis:
    path:     /devis
    defaults: { _controller: homePageBundle:User:devis }

user_progress_project:
    path:     /progressproject
    defaults: { _controller: homePageBundle:User:progress }

user_finish_project:
    path:     /finishproject
    defaults: { _controller: homePageBundle:User:finish }

user_sold_project:
    path:     /soldproject
    defaults: { _controller: homePageBundle:User:sold }

artist_profile:
    path:     /profile/{username}
    defaults: { _controller: CmaUserBundle:Profile:show }

artist_edit:
    path:     /profile/edit
    defaults: { _controller: CmaUserBundle:Profile:edit }

deleteuser:
    path:     /group/delete/{username}
    defaults: { _controller: homePageBundle:User:deleteadmin }

listGalleries:
    path:     /galleries/{page}-{topfilter}
    defaults: { _controller: homePageBundle:Gallery:index, page: 1,topfilter: null}
    requirements:
        page:  \d+
        price: \d+
        width: \d+
    methods:  [GET,POST]

listArtists:
    path:     /artist
    defaults: { _controller: homePageBundle:Artist:index }
