home_page_homepage:
    path:     /
    defaults: { _controller: homePageBundle:Default:index }

user_estimate_create:
    path:     /estimate/create
    defaults: {_controller: homePageBundle:Estimate:create }

user_estimate_edit:
    path:     /estimate/{id}
    defaults: {_controller: homePageBundle:Estimate:edit }

user_estimate_update:
    path:     /estimate/update/{id}
    defaults: {_controller: homePageBundle:Estimate:update }

user_estimate_delete:
    path:     /estimate/delete/{id}
    defaults: {_controller: homePageBundle:Estimate:delete }

estimate_detail:
    path:     /estimate/{id}/detail
    defaults: {_controller: homePageBundle:Estimate:detail }

estimate_validation:
    path:     /estimate/{id}/validation/{userp}
    defaults: {_controller: homePageBundle:Estimate:validation }
    schemes:  [https]

estimate_opinion:
    path:    /estimate/{id}/opinion
    defaults: {_controller: homePageBundle:Estimate:opinion }

user_devis:
    path:     /estimate
    defaults: { _controller: homePageBundle:Estimate:show }

user_parameter:
    path:     /parameter
    defaults: { _controller: homePageBundle:User:parameter }

user_basket:
    path:     /basket
    defaults: { _controller: homePageBundle:Basket:index }

piece_edit_id:
    path:     /piece/edit/{id}
    defaults: { _controller: homePageBundle:Piece:edit }

piece_create:
    path:     /piece/create
    defaults: { _controller: homePageBundle:Piece:create }

piece_delete:
    path:     /piece/delete/{id}
    defaults: { _controller: homePageBundle:Piece:delete }

proposal_create:
    path:     /estimate/{id}/proposal/create
    defaults: {_controller: homePageBundle:Proposal:create }

user_estimate_proposals:
    path:     /estimate/{id}/proposals
    defaults: {_controller: homePageBundle:Estimate:proposalList }

artist_proposal:
    path:     /proposals/list
    defaults: { _controller: homePageBundle:Proposal:list }

proposal_detail:
    path:     /proposal/{id}
    defaults: { _controller: homePageBundle:Proposal:detail }

proposal_delete:
    path:     /proposal/delete/{id}/{idp}
    defaults: {_controller: homePageBundle:Proposal:delete }

proposal_complain:
    path:    /proposal/{id}/complain
    defaults: { _controller: homePageBundle:Complain:create }

artist_proposal_show:
    path:     /proposal/{username}/{id}
    defaults: { _controller: homePageBundle:Proposal:show }

user_info:
    path:     /information
    defaults: { _controller: homePageBundle:User:information }

user_progress_project:
    path:     /progressproject
    defaults: { _controller: homePageBundle:User:progress }

user_finish_project:
    path:     /finishproject
    defaults: { _controller: homePageBundle:User:finish }

user_sold_project:
    path:     /soldproject
    defaults: { _controller: homePageBundle:User:sold }

artist_profile:
    path:     /profile/{username}
    defaults: { _controller: CmaUserBundle:Profile:show }

artist_profile_gallery:
    path:     /profile/{username}/gallery/{topfilter}
    defaults: { _controller: CmaUserBundle:Profile:gallery,topfilter: null }

artist_profile_opinions:
    path:     /profile/{username}/opinions
    defaults: { _controller: homePageBundle:Opinion:index }

artist_edit:
    path:     /profile/edit
    defaults: { _controller: CmaUserBundle:Profile:edit }

listGalleries:
    path:     /galleries/{page}-{topfilter}
    defaults: { _controller: homePageBundle:Gallery:index, page: 1,topfilter: null}
    requirements:
        page:  \d+
        price: \d+
        width: \d+
    methods:  [GET,POST]

listArtists:
    path:     /artist
    defaults: { _controller: homePageBundle:Artist:index }

concept:
    path:   /Concept
    defaults: { _controller: homePageBundle:Concept:index }

help:
    path:   /Help
    defaults: { _controller: homePageBundle:Help:index }

buy:
    path:   /buy/{pieceId}
    defaults: { _controller: homePageBundle:Buy:index }
